Add js
Fire-Ball-20001/WS_Frontend_Forms pull request #1
Opened 2022-06-21 01:24 UTC by Fire-Ball-20001

2022-06-22 02:53 UTC, manakina commented on .gitignore
> +server/db.json
Убери этот файл из игнора. Если сейчас подтянуть репозиторий и запустить сервер, то в таблице будут некорректные данные
![image](https://user-images.githubusercontent.com/105479546/174933046-531e4844-4b1c-47cc-8fc5-59128da54cfe.png)
Из-за того, что по умолчанию db.json выглядит следующим образом
![image](https://user-images.githubusercontent.com/105479546/174933172-4575bc67-8656-4e56-8947-1577ab3e068b.png)
Мы в запросе http://localhost:3000/posts получаем данные из posts, которые по умолчанию наполнены какими-то данными
```
  "posts": [
    {
      "id": 1,
      "title": "json-server",
      "author": "typicode"
    }
  ],
```

2022-06-22 03:10 UTC, manakina commented on scripts/scripts.js
> +  const back = document.getElementsByName("is_backend")[0];
Это можно переписать куда лаконичнее. Задай чекбоксам один класс, а в функции перебери элементы этого класса. И также с помощью .checked проверяй выбран кто-нибудь или нет

2022-06-22 13:49 UTC, WelcomeDev requested changes
Досмотрю завтра

2022-06-22 13:49 UTC, WelcomeDev commented on index.html
> +            <button name="req_text" class="wrapper__tooltip" type="button">?</button>
Зачем `button`? `button` подразумевает, что на это можно нажать и произойдет "чудо"
Я вот нажимаю и ничего не происходит. Значит, не кнопка

2022-06-22 13:49 UTC, WelcomeDev commented on index.html
> +        <section class="main__wrapper wrapper">
уважение за семантику 🔥

2022-06-22 13:49 UTC, WelcomeDev commented on index.html
> +      <fieldset class="main__border">
`fieldset` обычно испльзуется для набора (`set`) связанных полей, здесь это излишне

Нужно стараться сохранять семантику, но при этом некоторые `html`-элементы обладают "неприятными" особенностями, которые даже сбрасывающие стили не пофиксят. Например: `dialog` - он тупо не отобразится, если ему не указать атрибут `open`, `details` сюда же. Ну и `fieldset` - который делает рамку и позволяет вставлять пояснение. Поэтому зачастую используется не такой уж и большой набор тегов: `h`, `p`, `div`, `section`, `article`, `main`, `nav`, `header`, `footer` - это почти все. В общем, все, кто не модифицирует внешний вид

2022-06-22 13:49 UTC, WelcomeDev commented on scripts/scripts.js
> +      if (element.type === "text") {
Негибкий вариант. А если я попрошу добавить еще одно текстовое поле, которое не подходит под `TEXT_PATTERN`? Нужно переделать

Это не "лаба", где "препод" не меняет начальные условия. В реальном мире требования меняются, а такое решение является неочевидным и не плохо масштабируемым.

2022-06-22 13:49 UTC, WelcomeDev commented on scripts/work_data.js
> +  const res = Object.fromEntries(formData);
Сломается, если использовать массив
Стоит использовать `get` и `getAll`. Это мой косяк, не прогуглил как точно работает `fromEntries`

2022-06-22 13:49 UTC, WelcomeDev commented on index.html
> +                <input name="is_frontend" class="wrapper__checkbox" checked="true" type="checkbox" />
суть чекбокса в том, что на одно имя приходится несколько значений. Например:
```HTML
<input name="majority" value="fe"  type="checkbox" /> // frontend
<input name="majority" value="be"  type="checkbox" /> // backend
```
Нужно переделать

2022-06-22 13:49 UTC, WelcomeDev commented on scripts/tooltip_sc.js
> +function dateTooltip(mouse, input) {
Кул, не сразу заметил, но здорово 🔥🔥🔥

2022-06-22 13:49 UTC, WelcomeDev commented on scripts/tooltip_sc.js
> +      naprTooltip(mouse);
`napr`? Не стоит миксовать транслит и английский. "direction" или "majority"

2022-06-22 13:49 UTC, WelcomeDev commented on scripts/work_data.js
> +    if (element.is_frontend) {
сделать `checkbox`'ы c одним именем и заменить здесь на массив. Тогда можно упрастить значение ячейки с помощью `array.join` и тернарного оператора

2022-06-22 13:49 UTC, WelcomeDev commented on scripts/work_data.js
> +    if (element.is_pr == "work") {
`===`

2022-06-22 13:49 UTC, WelcomeDev commented on scripts/work_data.js
> +    if (element.is_pr == "work") {
Заменить на `switch`, он прям просится в `select`

2022-06-22 13:49 UTC, WelcomeDev commented on scripts/work_data.js
> +    const oneRow = {
можно не писать название поля, если тмя переменной совпадает, т.е.
~is_pr: is_pr~ ->`is_pr`

2022-06-22 13:49 UTC, WelcomeDev commented on styles/styles.css
> +p {
не понятно, чем файл `main`отличается от `styles`, нужно переименовать

2022-06-22 13:49 UTC, WelcomeDev commented on scripts/work_data.js
> +async function sendData(data) {
`work_data` 🤔🤔🤔 з0чем данные работают? По названию скрипта не понятно, что тут происходит

2022-06-22 13:49 UTC, WelcomeDev commented on scripts/scripts.js
> +const TEXT_PATTERN = /^[А-Яа-я]+$/;
Тут валидация происходит, вот пусть он и называется соответственно. Лучше избегать каких-то общих названий.
Если это только не единственный файл, и он не называется `index`, ибо это стандарт

2022-06-22 13:49 UTC, WelcomeDev commented on scripts/scripts.js
> +  const form = document.getElementById("form");
Объявление переменной слишком далеко от места ее использования. Стив Макконнел в книжке "Совершенный Код" скажет, что это сильно ухудшает читаемость. И я с ним согласен

2022-06-22 13:49 UTC, WelcomeDev commented on scripts/scripts.js
> +  document.getElementById("send_button").onclick = validity;
`validity` - имя существительное. Нельзя "выполнить" существительное, ~validity~ -> "validate"

2022-06-22 13:49 UTC, WelcomeDev commented on scripts/tooltip_sc.js
> +  const req_text = document.getElementsByName("req_text");
в принципе, можно оставить так. Но вот мои аргументы, почему я считаю, что можно сделать проще:
1. js и html следуют неформальному контракту. js верит, что в html будут элементы с именем `req_text`. А если вдруг в форме встретится такое имя? 💀Неформальные контракты - сомнительная тема, о них легко можно забыть
2. нужно, собственно, поддерживать этот контракт - везде писать элемент именно с таким именем, когда это имя - надуманная и лишняя абстракция

Что предлагаю? Получить этот элемент через `input`. Помним, что у нас есть полный контроль над деревом через dom

![image](https://user-images.githubusercontent.com/65521226/175043381-1f563970-8c59-4352-a76c-8ab01a9db0a4.png)

Браузер - мощнейший инструмент. Даже если не знаешь о каких-то свойствах, их всегда можно подсмотреть прям в консоли
![image](https://user-images.githubusercontent.com/65521226/175044408-2797b1bc-c0de-413a-9bfe-73d0a6123d11.png)

2022-06-22 13:49 UTC, WelcomeDev commented on index.html
> +          <input name="otch" class="wrapper__input" type="text" />
мешать русский и английский - плохая практика. Если с английским не очень, то лучше и не станет, если пользоваться такими "костылями"
~otch~ -> `middleName`

2022-06-23 03:49 UTC, WelcomeDev requested changes
За отображение инфы об ошибке с помощи мыши - жирный лайк. Прям очень круто, красава 🔥
Хочется, чтобы именно сам значек еще менялся в зависимости от того, валидно поле или нет, но это уже на твое усмотрение. В принципе, изменения boreder'а - тоже достаточно

Самое большое замечание - "разбросанная" валидация. Это нужно исправить. Я считаю, что если проставлять `regex` через js, то нужно это делать по именам инпутов, а не по типу; и из этого же js управлять `required` и внешним видом в зависимости от этого.
И лучше не использовать неформальные контракты

2022-06-23 03:49 UTC, WelcomeDev commented on index.html
> +          <p class="wrapper__label">Телефон*</p>
`wrapper__label`, но при этом `<p>` 🤔 Непорядок. Подписи к инпутам всегда `<label>`

2022-06-23 03:49 UTC, WelcomeDev commented on index.html
> +          <p class="wrapper__label">Телефон*</p>
Звездочка - тема простая, слабо относится к формам, но мне понравилась😅

По сути: негибкий вариант. Получается, что валидация зависит и от разметки, и от js. Так быть не должно (ну или по минималке). Поэтому сделать или отдельным элементом и отображать через css-селектор на основе `input[required]` - но это будет очень сложно сделать через css. 
ИЛИ
Через JS. Это делается сильно проще

2022-06-23 03:49 UTC, WelcomeDev commented on scripts/scripts.js
> +    console.log(event);
`console.log` убираем из пр

2022-06-23 03:49 UTC, WelcomeDev commented on scripts/scripts.js
> +  for(const checkbox of checkboxes) {
как вариат
```JS
const isAnyChecked = checkboxes.filter(ch=>ch.checked).length()>0
// или
const isAnyChecked = checkboxes.map(ch => ch.checked).reduce((first, second) => first || second, false);
```

исправлять по желанию

2022-06-23 03:49 UTC, WelcomeDev commented on scripts/scripts.js
> +      if (element.type === "text") {
Лучше на основе имен формы инициализировать валидацию, а не на основе типа. Имена уникальны на форму, а тип - нет

Можешь посмотреть мой [пример](https://github.com/WelcomeDev/ws-students-forms), а можешь у ребят.

2022-06-23 03:49 UTC, WelcomeDev commented on scripts/tooltip_sc.js
> +  const req_text = document.getElementsByName("req_text");
Предложенный мной вариант будет значительно короче, если мы установим для `input` еще и `data-error-message` - аттрибут, который будет содержать сообщение об ошибке. В моем репозитории есть пример

Сейчас у тебя получается, что на каждый вид поля мы вручную выбираем и вызываем нужный метод. Но по сути, мы делаем одно и то же. Для каждого типа инпута есть:
1. перебор
2. добавление слушателя
3. получение элемента
4. вызов тултипа

Целых 4 одинаковых действия. Слишком много однообразного кода

2022-06-23 03:49 UTC, WelcomeDev commented on scripts/work_data.js
> +    napr = napr.substring(0, napr.length - 2);
Ну, это прям костыль, кста. Так что однозначно `Array.join`

2022-07-25 05:43 UTC, Imagery-na approved these changes

2022-07-25 09:21 UTC, manakina commented on scripts/tooltip_sc.js
> +  if (input.value === "") {
Можно с тернарным
```
data_tooltip.push(input.value  ? createText("Всё хорошо", true) : createText("Необходимо значение", false));
```

2022-07-25 09:40 UTC, manakina approved these changes
Добавь cursor:pointer на вопросики

2022-07-25 09:45 UTC, merged